baseURL = "https://snox.cf/"
languageCode = "en-us"
title = "snox is cool"
theme = "hugo-theme-shell"
ignoreErrors = ["error-remote-getjson"]

[author]
  name = "Andrew (Snox)"
  homepage = "https://snox.cf"
  twitch = "https://twitch.tv/SimplySnox"
  discord = "https://discord.gg/Ggj23D325t"
  twitter = "https://twitter.com/SimplySnox"

[Params]
    [Params.Navbar]
    use = true
    description = "snox's portfolio"

    [Params.Terminal]
    scheme = "Molokai"
    
    userName = "snox"
    pcName = "desktop"
    workDir = "home"
    profile = "about.txt"

    description = """
    Hi there! I'm Snox. I enjoy coding
    different projects for myself and
    close friends.
    
    I commonly use languages and frameworks
    such as Node.js, Javascript, Python, and more.
    """

    [Params.Tree]
    use = true
    folderName = "socials"
    files = [
        ["Github", "https://github.com/SimplySnox/"],
        ["Twitch", "https://twitch.tv/SimplySnox/"],
        ["Discord", "https://discord.gg/Ggj23D325t"]
    ]

    folderName = "experience"
    description = """
    I have experience in various different languages
    (mainly Javascript, Python, etc), but I also have a
    lot of experience moderating & managing many different
    discord servers. Some of these discords are listed below.
    """
    files = [
        ["(Previously managed) QuietStates", "https://discord.gg/cpnNzNMvQS"],
        ["(Previously administered) Gryffyn's Studio", "https://discord.gg/NZA9z569Gg"],
        ["(Current: Admin) Shrimp's Island", "https://discord.gg/q4qwQwjktX"]
    ]
