baseURL = "https://snox.cf/"
languageCode = "en-us"
title = "snox is cool"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"

    [Params.Tree]
    use = true
    files = [
        ["Github", "https://github.com/SimplySnox/"],
        ["Twitch", "https://twitch.tv/SimplySnox/"],
        ["Discord", "https://discord.gg/Ggj23D325t"],
        ["Hugo", "/works/hugo.md"]
    ]
